### ISSUE TITLE
v1 CHECKLIST

### ISSUE THREAD

**Issue by kieranpotts** [neroui/nero-css#8]
#### Demos
- [x] Separate demos by topic: typography, layouts, etc.
- [x] Rename Nero.css playground
- [x] Horizontal view

#### Style Guide
- [x] Style Guide in ``./guide/`` directory (moved to separate directory)

#### Docs
- [ ] Fonts are expected to be loaded separately

#### Distribution

- [ ] Serve from CDNs such as GitHub Pages, unpkg.com
- [ ] Make available via both NPM and Yarn
